"""
Automatic LOB Data Collector for Options.

Runs continuously in the background. Automatically detects U.S. equity market hours
(9:30 AM - 4:00 PM ET, Mon-Fri, excluding holidays) and collects option bid/ask snapshots.

ALSO COLLECTS THE UNDERLYING SPOT PRICE at each snapshot.

The saved Parquet file is fully compatible with the LOBSnapshot class.
The collector derives its schema from EXPECTED_COLUMNS,
ensuring the data contract is always in sync.

Usage:
    python scripts/collect_lob_data.py

The script will run indefinitely. Stop it with Ctrl+C.
"""
# A quick hack
import sys
from pathlib import Path

project_root = Path(__file__).resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Imports
import yfinance as yf
import pandas as pd
import time
import logging
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo
from typing import List, Dict, Any

# Import the data structures to keep the column definitions in sync
from src.data.lob_snapshot import EXPECTED_COLUMNS
from src.config import settings

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

SYMBOL = "SPY"
INTERVAL_SECONDS = settings.LOB_INTERVAL_SECONDS
OUTPUT_DIR = Path("data/lob_history")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Market hours in Eastern Time
MARKET_OPEN = (9, 30)   # 9:30 AM
MARKET_CLOSE = (16, 0)  # 4:00 PM

# Mapping from LOBSnapshot column names to yfinance column names
# Columns with `None` are generated by us (not from yfinance)
YF_COLUMN_MAP = {
    'timestamp': None,       # Generated by us
    'spot_price': None,      # Generated by us
    'expiry': None,          # Generated by us
    'strike': 'strike',
    'type': None,            # Generated by us (call/put)
    'bid': 'bid',
    'ask': 'ask',
    'bid_size': 'bidSize',
    'ask_size': 'askSize',
    'volume': 'volume',
    'open_interest': 'openInterest',
    'implied_vol': 'impliedVolatility',
    'last_price': 'lastPrice',
}

# Logging setup
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# -----------------------------------------------------------------------------
# Market Hours Utilities
# -----------------------------------------------------------------------------

def is_market_open(now: datetime) -> bool:
    """Returns True if the market is currently open (ET time, Mon-Fri, 9:30 AM - 4:00 PM)."""
    if now.weekday() >= 5:  # Saturday or Sunday
        return False

    current_time = (now.hour, now.minute)
    if current_time < MARKET_OPEN or current_time >= MARKET_CLOSE:
        return False

    return True


def wait_until_market_open(now: datetime) -> float:
    """Calculates the number of seconds to sleep until the next market open."""
    if is_market_open(now):
        return 0.0

    # Calculate the next market open
    target = now.replace(hour=MARKET_OPEN[0], minute=MARKET_OPEN[1], second=0, microsecond=0)

    # If we are before the open today (but it's a weekday), return today's open
    if now.weekday() < 5 and now < target:
        pass  # target is already today's open
    else:
        # Move to the next weekday (Mon-Fri)
        days_ahead = 0
        while True:
            days_ahead += 1
            test_date = now + timedelta(days=days_ahead)
            if test_date.weekday() < 5:  # Monday-Friday
                target = test_date.replace(hour=MARKET_OPEN[0], minute=MARKET_OPEN[1], second=0, microsecond=0)
                break

    sleep_seconds = (target - now).total_seconds()
    return max(sleep_seconds, 0)


# -----------------------------------------------------------------------------
# Data Collection
# -----------------------------------------------------------------------------

def collect_snapshot(ticker: yf.Ticker) -> pd.DataFrame:
    """
    Fetches one full snapshot of the option chain and the spot price.
    Returns a DataFrame with columns matching LOBSnapshot.EXPECTED_COLUMNS.
    """
    records: List[Dict[str, Any]] = []
    spot_price = None

    try:
        # 1. Fetch spot price
        hist = ticker.history(period="1d")
        if not hist.empty:
            spot_price = float(hist['Close'].iloc[-1])
        else:
            logger.warning("Could not fetch spot price. Skipping this snapshot.")
            return pd.DataFrame()

        # 2. Fetch option chain
        expiries = ticker.options
        if not expiries:
            logger.warning("No expiries available. Market might be closed or data missing.")
            return pd.DataFrame()

        for exp in expiries:
            chain = ticker.option_chain(exp)
            for df, opt_type in [(chain.calls, "call"), (chain.puts, "put")]:
                for _, row in df.iterrows():
                    # Skip if bid/ask are zero (stale or no market)
                    if row.get("bid", 0) <= 0 and row.get("ask", 0) <= 0:
                        continue

                    # Build the record using the schema from LOBSnapshot
                    record = {
                        "timestamp": datetime.now(ZoneInfo("US/Eastern")).isoformat(),
                        "spot_price": spot_price,
                        "expiry": exp,
                        "strike": row["strike"],
                        "type": opt_type,
                    }

                    # Add all fields from EXPECTED_COLUMNS (using the mapping)
                    for col in EXPECTED_COLUMNS:
                        if col in record:
                            continue
                        yf_col = YF_COLUMN_MAP.get(col)
                        if yf_col is not None:
                            record[col] = row.get(yf_col, 0)
                        else:
                            # This should not happen for columns in EXPECTED_COLUMNS
                            record[col] = 0

                    records.append(record)

        if not records:
            logger.warning("No valid option records found (possibly a market holiday).")
            return pd.DataFrame()

        # Convert to DataFrame and ensure column order for consistency
        df = pd.DataFrame(records)

        # Ensure all expected columns exist (fill missing with 0 if necessary)
        for col in EXPECTED_COLUMNS:
            if col not in df.columns:
                df[col] = 0

        # Reorder columns to match the expected order
        df = df[EXPECTED_COLUMNS]

        return df

    except Exception as e:
        logger.error(f"Error fetching data: {e}")
        return pd.DataFrame()


def save_snapshot(df: pd.DataFrame):
    """Appends the snapshot to a Parquet file for today."""
    if df.empty:
        return

    today_str = datetime.now(ZoneInfo("US/Eastern")).date().isoformat()
    file_path = OUTPUT_DIR / f"{SYMBOL}_{today_str}.parquet"

    if file_path.exists():
        existing = pd.read_parquet(file_path)
        combined = pd.concat([existing, df], ignore_index=True)
        combined.to_parquet(file_path, index=False)
    else:
        df.to_parquet(file_path, index=False)

    spot = df['spot_price'].iloc[0] if not df.empty else 0.0
    logger.info(f"Saved {len(df)} records (spot={spot:.2f}) to {file_path.name}")


# -----------------------------------------------------------------------------
# Main Loop
# -----------------------------------------------------------------------------

def main():
    logger.info(f"Starting LOB collector for {SYMBOL}...")
    logger.info(f"Output directory: {OUTPUT_DIR}")
    logger.info("Press Ctrl+C to stop.")

    ticker = yf.Ticker(SYMBOL)

    while True:
        try:
            now = datetime.now(ZoneInfo("US/Eastern"))
            is_open = is_market_open(now)

            if is_open:
                logger.debug("Market is open. Collecting snapshot...")
                df = collect_snapshot(ticker)
                if not df.empty:
                    save_snapshot(df)
                time.sleep(INTERVAL_SECONDS)
            else:
                sleep_seconds = wait_until_market_open(now)
                if sleep_seconds > 0:
                    next_open_time = (now + timedelta(seconds=sleep_seconds)).strftime("%Y-%m-%d %H:%M:%S %Z")
                    logger.info(f"Market closed. Sleeping until {next_open_time} ({sleep_seconds/3600:.1f} hours).")
                    while sleep_seconds > 0:
                        chunk = min(sleep_seconds, 3600)
                        time.sleep(chunk)
                        sleep_seconds -= chunk
                        if is_market_open(datetime.now(ZoneInfo("US/Eastern"))):
                            break
                else:
                    time.sleep(60)

        except KeyboardInterrupt:
            logger.info("Stopped by user.")
            break
        except Exception as e:
            logger.error(f"Unexpected error in main loop: {e}", exc_info=True)
            time.sleep(60)


if __name__ == "__main__":
    main()